version: '3.5'
services:
  upload-media:
      build:
        context: mongo_upload_media
        dockerfile: Dockerfile
      network_mode: host
      environment:
        KAFKA_TOPIC: media-upload
        KAFKA_GROUP_ID: upload
        KAFKA_HOST: 127.0.0.1
        KAFKA_PORT: 9092
        MONGO_USER: usr
        MONGO_PASSWORD:
        MONGO_HOST: cloud-dev-mongo-node-1
        MONGO_PORT: 27017
        COUNT_PHOTO_WORKER: 90
        COUNT_MESSAGE_WORKER: 90
        COUNT_USER_WORKER: 90
      restart: on-failure
